export const portfolio = {
  university: 'Universidad Tecnológica del Perú',
  universityShort: 'UTP',
  student: 'Denis Espinoza',
  studentFullName: 'Denis Yeyson Espinoza Ponciano',
  career: 'Ingeniería de Software',
  course: 'Matemática 2',
  teacher: 'Completa el nombre del docente',
  section: 'Completa tu sección',
  semester: '2026-II',
  year: 2026,
  firstWeekDate: '2026-08-10',
  weeks: 18,
  sessionsPerWeek: 2,
  exercisesPerSession: 5,
  subtitle: 'Portafolio académico de teoría, ejercicios y visualizaciones interactivas.',
  description: 'Un recorrido de 18 semanas por la matemática universitaria, explicado paso a paso.',
  geogebraProfile: 'https://www.geogebra.org/',
  units: [
    { number: 1, title: 'Geometría analítica', start: 1, end: 4, color: 'cyan' },
    { number: 2, title: 'Funciones y relaciones', start: 5, end: 8, color: 'violet' },
    { number: 3, title: 'Evaluación parcial', start: 9, end: 9, color: 'amber' },
    { number: 4, title: 'Cálculo diferencial', start: 10, end: 13, color: 'emerald' },
    { number: 5, title: 'Aplicaciones del cálculo', start: 14, end: 17, color: 'rose' },
    { number: 6, title: 'Evaluación final', start: 18, end: 18, color: 'amber' },
  ],
} as const;
